<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

// phpcs:disable Generic.Files.LineLength

/** @var Escaper $escaper */
/** @var Template $block */

$title = "This is the default Hyvä Theme.";
$link = "https://hyva.io/";
?>
<section class="text-gray-700 body-font flex relative z-10">
    <div class="container mx-auto flex px-5 mt-8 xl:-mt-12 md:flex-row flex-col items-center">
        <div class="w-full xl:w-1/2 md:w-1/3 sm:w-5/6 mb-10 md:mb-0">
            <img class="object-cover object-center rounded shadow-lg rounded-md"
                 src="<?= $escaper->escapeHtmlAttr($block->getViewFileUrl('images/hyva-logo.svg')) ?>"
                 alt=""
                 width="500"
                 height="500"
                 loading="lazy"
                 aria-hidden="true"
            >
        </div>
        <div class="xl:grow md:w-2/3 lg:pl-24 md:pl-16 flex flex-col md:items-start md:text-left items-center text-center">
            <h2 class="title-font sm:text-4xl text-3xl mb-4 font-medium text-gray-900"><?= $escaper->escapeHtml($title) ?></h2>
            <p class="mb-8 leading-relaxed">
                We've rebuilt the standard Magento 2 frontend with a new technology stack. It combines the best parts of Magento frontend development with modern tools that developers love, like AlpineJS and TailwindCSS.
            </p>
            <p class="mb-8 leading-relaxed">
                It's high-performant out of the box and reduces the development time of custom Magento frontends. It will make you and your customers happy.
            </p>
            <div class="flex justify-center">
                <a href="<?= $escaper->escapeUrl($link) ?>" class="inline-flex btn btn-primary">Buy it</a>
                <span class="flex self-center ml-4 ">or</span>
                <a href="<?= $escaper->escapeUrl($link) ?>" class="ml-4 inline-flex btn btn-secondary">Visit Hyvä</a>
            </div>
        </div>
    </div>
</section>
