<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HeroiconsOutline;
use Magento\Framework\Escaper;
use Magento\Sales\Block\Order\Creditmemo\Items;

/** @var Escaper $escaper */
/** @var Items $block */
/** @var ViewModelRegistry $viewModels */

/** @var HeroiconsOutline $heroicons */
$heroicons = $viewModels->require(HeroiconsOutline::class);

$order = $block->getOrder();
?>
<?php foreach ($order->getCreditmemosCollection() as $creditmemo): ?>
    <div class="order-title text-center md:text-left font-semibold">
        <?= $escaper->escapeHtml(__('Refund #')) ?>
        <?= $escaper->escapeHtml($creditmemo->getIncrementId()) ?>
        <a href="<?= $escaper->escapeUrl($block->getPrintCreditmemoUrl($creditmemo)) ?>"
           class="text-primary inline-block ml-2 pl-2 border-l text-sm font-normal"
            target="_blank"
            rel="noopener">
            <?= $heroicons->printerHtml('inline-block', 20, 20); ?>
            <span class="inline-block ml-1 underline">
                <?= $escaper->escapeHtml(__('Print Refund')) ?>
            </span>
        </a>
    </div>

    <?= $block->getCommentsHtml($creditmemo) ?>

    <div class="order-items creditmemo">
        <div class="hidden lg:grid grid-cols-7 text-sm text-secondary ">
            <div class="p-2 col-span-2"><?= $escaper->escapeHtml(__('Product Name')) ?></div>
            <div class="p-2"><?= $escaper->escapeHtml(__('Price')) ?></div>
            <div class="p-2"><?= $escaper->escapeHtml(__('Qty')) ?></div>
            <div class="p-2 text-right"><?= $escaper->escapeHtml(__('Subtotal')) ?></div>
            <div class="p-2 text-right"><?= $escaper->escapeHtml(__('Discount Amount')) ?></div>
            <div class="p-2 text-right"><?= $escaper->escapeHtml(__('Row Total')) ?></div>
        </div>
        <?php $items = $creditmemo->getAllItems(); ?>
        <?php foreach ($items as $item): ?>
            <?php if (!$item->getOrderItem()->getParentItem()): ?>
                <?= $block->getItemHtml($item) ?>
            <?php endif; ?>
        <?php endforeach; ?>
        <div class="flex justify-end border-t border-container">
            <div class="lg:w-1/3">
                <div class="grid grid-cols-2 text-right p-2 gap-2">
                    <?= $block->getTotalsHtml($creditmemo) ?>
                </div>
            </div>
        </div>
    </div>
<?php endforeach; ?>
