<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Magento\Theme\Block\Html\Footer;
use Magento\Framework\Escaper;

/** @var Footer $block */
/** @var Escaper $escaper */
?>
<small class="text-sm text-gray-800 sm:ml-6 sm:mt-0 mt-4">
    © 2020 Hyva Themes B.V. —
    <a
        href="https://twitter.com/hyva_io"
        target="_blank"
        rel="noopener noreferrer"
        class="text-gray-700 ml-1"
        aria-label="<?= $escaper->escapeHtmlAttr(__('Hyva twitter profile'). ', ' . __('opens in new window')) ?>"
    >@hyva_io</a>
    <?php /* Enable the following line to show the copyright information configured in the admin
    <span><?= $escaper->escapeHtml($block->getCopyright()) ?></span>
    */ ?>
</small>
