<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

use Magento\Framework\Escaper;
use Magento\Sales\Block\Order\Invoice;

/** @var Invoice $block */
/** @var Escaper $escaper */
?>
<?php $order = $block->getOrder() ?>
<div class="md:flex md:justify-between items-center mb-3">
    <div class="lg:flex items-center text-center md:text-left">
        <div class="lg:inline-block">
            <div class="text-2xl"><?= $escaper->escapeHtml(__('Order # %1', $order->getRealOrderId())) ?></div>
            <?= $block->getChildHtml('order.date') ?>
        </div>
        <div class="mt-3 md:mt-0 lg:inline-block lg:ml-5">
            <?= $block->getChildHtml('order.status') ?>
        </div>
    </div>
    <?= $block->getChildHtml('sales.invoice.buttons') ?>
</div>
<div class="order-details-items invoice bg-container-lighter">
    <div class="-mx-4">
        <?= $block->getChildHtml('order_top_items') ?>
    </div>
    <div class="p-4 card">
        <div class="mb-4">
            <?= $block->getChildHtml('sales.order.info') ?>
        </div>
        <?= $block->getChildHtml('invoice_items') ?>
        <div class="actions-toolbar">
            <div class="secondary">
                <a class="action back" href="<?= $escaper->escapeUrl($block->getBackUrl()) ?>">
                    <span><?= $escaper->escapeHtml($block->getBackTitle()) ?></span>
                </a>
            </div>
        </div>
    </div>
</div>
