<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

use Magento\Framework\Escaper;
use Magento\GiftMessage\Helper\Message;
use Magento\Sales\Block\Order\View;

// phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis
// phpcs:disable Magento2.Templates.ThisInTemplate.FoundHelper

/** @var View $block */
/** @var Escaper $escaper */

$giftMessageHelper = $this->helper(Message::class);
?>
<?php $order = $block->getOrder() ?>
<div class="md:flex md:justify-between items-center mb-3">
    <div class="lg:flex items-center text-center md:text-left">
        <div class="lg:inline-block">
            <div class="text-2xl"><?= $escaper->escapeHtml(__('Order # %1', $order->getRealOrderId())) ?></div>
            <?= $block->getChildHtml('order.date') ?>
        </div>
        <div class="mt-3 md:mt-0 lg:inline-block lg:ml-5">
            <?= $block->getChildHtml('order.status') ?>
        </div>
    </div>
    <?php if (!$block->getData('is_context_shipment')): ?>
        <?= $block->getChildHtml('sales.order.buttons') ?>
    <?php else: ?>
        <?= $block->getChildHtml('sales.shipment.buttons') ?>
    <?php endif; ?>
</div>
<div class="order-details-items ordered bg-container-lighter">
    <div class="-mx-4">
        <?= $block->getChildHtml('order_top_items') ?>
    </div>
    <div class="p-4 card">
        <div class="mb-4">
            <?= $block->getChildHtml('sales.order.info') ?>
        </div>

        <?= $block->getChildHtml('order.comments') ?>

        <?php if (!$block->getData('is_context_shipment')): ?>
            <div class="order-title">
                <p class="text-lg mt-8 mb-2"><?= $escaper->escapeHtml(__('Items Ordered')) ?></p>
                <?php if (!empty($order->getTracksCollection()->getItems())): ?>
                    <?= $block->getChildHtml('tracking-info-link') ?>
                <?php endif; ?>
            </div>
        <?php endif; ?>

        <?= $block->getChildHtml('order_items') ?>

        <?php if ($giftMessageHelper->isMessagesAllowed('order', $order) && $order->getGiftMessageId()): ?>
            <div class="block block-order-details-gift-message">
                <div class="block-title"><strong><?= $escaper->escapeHtml(__('Gift Message for This Order')) ?></strong>
                </div>
                <?php
                $giftMessage =
                    $giftMessageHelper->getGiftMessageForEntity($order);
                ?>
                <div class="block-content">
                    <dl class="item-options">
                        <dt class="item-sender">
                            <strong class="label">
                                <?= $escaper->escapeHtml(__('From')) ?>
                            </strong>
                            <?= $escaper->escapeHtml($giftMessage->getSender()) ?>
                        </dt>
                        <dt class="item-recipient">
                            <strong class="label">
                                <?= $escaper->escapeHtml(__('To')) ?>
                            </strong>
                            <?= $escaper->escapeHtml($giftMessage->getRecipient()) ?>
                        </dt>
                        <dd class="item-message">
                            <?= /* @noEscape */ $giftMessageHelper->getEscapedGiftMessage($order) ?>
                        </dd>
                    </dl>
                </div>
            </div>
        <?php endif; ?>
        <div class="actions-toolbar">
            <div class="secondary">
                <a class="action back" href="<?= $escaper->escapeUrl($block->getBackUrl()) ?>">
                    <span><?= $escaper->escapeHtml($block->getBackTitle()) ?></span>
                </a>
            </div>
        </div>
    </div>
</div>
