<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Hyva\Theme\Block\SortableItem;
use Magento\Framework\Escaper;

/** @var SortableItem $block */
/** @var Escaper $escaper */
?>

<span id="<?= $escaper->escapeHtmlAttr($block->getNameInLayout()) ?>"
      class="delimiter block border-b border-container w-full my-2"
></span>
