<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\Currency;
use Hyva\Theme\ViewModel\HeroiconsSolid;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

// phpcs:disable Generic.Files.LineLength.TooLong

/** @var Template $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

/** @var HeroiconsSolid $heroiconsSolid */
$heroiconsSolid = $viewModels->require(HeroiconsSolid::class);

/** @var Currency $currencyViewModel */
$currencyViewModel = $viewModels->require(Currency::class);
?>
<?php if ($currencyViewModel->getCurrencyCount() > 1): ?>
    <?php $currencies = $currencyViewModel->getCurrencies(); ?>
    <?php $currentCurrencyCode = $currencyViewModel->getCurrentCurrencyCode(); ?>
    <div x-data="{ open: false }"
         class="w-full sm:w-1/2 md:w-full pr-4"
    >
        <h2
            id="currency-heading"
            class="title-font font-medium text-gray-900 tracking-widest text-sm mb-3 uppercase"
        >
            <?= $escaper->escapeHtml(__('Currency')) ?>
        </h2>
        <div class="relative inline-block text-left">
            <div>
                <button @click.prevent="open = !open"
                        @click.outside="open = false"
                        @keydown.window.escape="open=false"
                        type="button"
                        class="inline-flex justify-center w-full form-select px-4 py-2 bg-white focus:outline-none"
                        aria-haspopup="true"
                        :aria-expanded="open"
                >
                    <?= $escaper->escapeHtml($currentCurrencyCode) ?>
                    <?php if ($currencies[$currentCurrencyCode]): ?>
                        - <?= $escaper->escapeHtml($currencies[$currentCurrencyCode]) ?>
                    <?php endif; ?>
                    <?= $heroiconsSolid->chevronDownHtml("flex self-center h-5 w-5 -mr-1 ml-2", 25, 25) ?>
                </button>
            </div>
            <nav x-cloak=""
                 x-show="open"
                 class="absolute right-0 top-full z-20 w-56 py-2 mt-1 overflow-auto origin-top-left rounded-sm shadow-lg sm:w-48 lg:mt-3 bg-container-lighter"
                 aria-labelledby="currency-heading"
            >
                <div class="my-1">
                    <?php foreach ($currencies as $code => $name): ?>
                        <?php if ($code != $currentCurrencyCode): ?>
                            <button
                               role="link"
                               class="block px-4 py-2 lg:px-5 lg:py-2 hover:bg-gray-100"
                               aria-describedby="currency-heading"
                               @click.prevent='hyva.postForm(<?= /* @noEscape */ $currencyViewModel->getSwitchCurrencyPostData($code) ?>)'
                            >
                                <?= $escaper->escapeHtml($code) ?> - <?= $escaper->escapeHtml($name) ?>
                            </button>
                        <?php endif; ?>
                    <?php endforeach; ?>
                </div>
            </nav>
        </div>
    </div>
<?php endif; ?>
