<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

use Magento\Framework\Escaper;
use Magento\Wishlist\Block\Customer\Wishlist\Button;

/** @var Escaper $escaper */
/** @var Button $block */
?>

<?php if ($block->getWishlist()->getItemsCount()): ?>
    <button type="submit"
            name="do"
            title="<?= $escaper->escapeHtmlAttr(__('Update Wish List')) ?>"
            class="update btn btn-secondary">
        <span><?= $escaper->escapeHtml(__('Update Wish List')) ?></span>
    </button>
<?php endif;?>
