<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HeroiconsOutline;
use Magento\Downloadable\Block\Catalog\Product\Samples;
use Magento\Framework\Escaper;

/** @var Samples $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

/** @var HeroiconsOutline $heroicons */
$heroicons = $viewModels->require(HeroiconsOutline::class);
?>

<?php if ($block->hasSamples()): ?>
    <div class="items samples">
        <h2 class="text-gray-900 text-xl title-font font-medium mb-4">
            <?= $escaper->escapeHtml($block->getSamplesTitle()) ?>
        </h2>
        <?php $samples = $block->getSamples() ?>
        <div class="flex flex-col border-t border-gray-300 py-2 last:mb-6 last:border-b">
        <?php foreach ($samples as $sample): ?>
            <div class="block w-full text-left text-gray-700 mb-2">
                <a href="<?= $escaper->escapeHtml($block->getSampleUrl($sample)) ?>"
                   download
                   <?= $block->getIsOpenInNewWindow() ? 'onclick="this.target=\'_blank\'"' : '' ?>
                   class="item-link samples-item-link">
                    <?= $heroicons->documentDownloadHtml(); ?>
                    <?= $escaper->escapeHtml($sample->getTitle()) ?>
                </a>
            </div>
        <?php endforeach; ?>
        </div>
    </div>
<?php endif; ?>
