<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HeroiconsOutline;
use Hyva\Theme\ViewModel\StoreConfig;
use Magento\Checkout\Block\Cart\Sidebar as SidebarCart;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Escaper $escaper */
/** @var Template $block */
/** @var ViewModelRegistry $viewModels */

/** @var HeroiconsOutline $heroicons */
$heroicons = $viewModels->require(HeroiconsOutline::class);

/** @var StoreConfig $storeConfig */
$storeConfig = $viewModels->require(StoreConfig::class);
$showMiniCart = $storeConfig->getStoreConfig(SidebarCart::XML_PATH_CHECKOUT_SIDEBAR_DISPLAY);
?>
<script>
    function initHeader () {
        return {
            searchOpen: false,
            cart: {},
            isCartOpen: false,
            getData(data) {
                if (data.cart) { this.cart = data.cart }
            },
            isCartEmpty() {
                return !this.cart.summary_count
            },
            toggleCart(event) {
                if (event.detail && event.detail.isOpen !== undefined) {
                    this.isCartOpen = event.detail.isOpen
                    if (!this.isCartOpen && this.$refs && this.$refs.cartButton) {
                        this.$refs.cartButton.focus()
                    }
                } else {
                    <?php
                    /*
                     * The toggle-cart event was previously dispatched without parameter to open the drawer (not toggle).
                     * Keeping this in here for backwards compatibility.
                     */
                    ?>
                    this.isCartOpen = true
                }
            }
        }
    }
    function initCompareHeader() {
        return {
            compareProducts: null,
            itemCount: 0,
            receiveCompareData(data) {
                if (data['compare-products']) {
                    this.compareProducts = data['compare-products'];
                    this.itemCount = this.compareProducts.count;
                }
            }
        }
    }
</script>
<div id="header"
     class="relative z-30 w-full border-b shadow bg-container-lighter border-container-lighter"
     x-data="initHeader()"
     @private-content-loaded.window="getData(event.detail.data)"
>
    <div class="container flex flex-wrap items-center justify-between w-full px-6 py-3 mx-auto mt-0">
        <!--Logo-->
        <?= $block->getChildHtml('logo'); ?>

        <!--Main Navigation-->
        <?= $block->getChildHtml('topmenu') ?>

        <div class="flex items-center order-3">
            <!--Compare Icon-->
            <a id="compare-link"
               class="relative invisible inline-block mx-1 no-underline sm:ml-3 hover:text-black"
               :class="{ 'invisible': !(itemCount > 0) }"
               href="<?= $escaper->escapeUrl($block->getUrl('catalog/product_compare/index')) ?>"
               title="<?= $escaper->escapeHtml(__('Compare Products')) ?>"
               x-data="initCompareHeader()"
               @private-content-loaded.window="receiveCompareData($event.detail.data)"
            >
                <?= $heroicons->scaleHtml(
                    "w-8 h-8 md:h-6 md:w-6 hover:text-black",
                    25,
                    25
                ) ?>

                <span class="sr-only label">
                   <?= $escaper->escapeHtml(__('Compare Products')) ?>
                </span>

                <span class="absolute top-0 right-0 h-5 px-2 py-1 -mt-5 -mr-4 text-xs font-semibold
                    leading-none text-center text-white uppercase transform -translate-x-1
                    translate-y-1/2 bg-yellow-500 rounded-full"
                >
                    <span x-text="itemCount"></span>
                    <span x-show="itemCount === 1" class="sr-only">
                        <?= $escaper->escapeHtml(__('item')) ?>
                    </span>
                    <span x-show="itemCount > 1" class="sr-only">
                        <?= $escaper->escapeHtml(__('items')) ?>
                    </span>
                </span>
            </a>

            <!--Search Icon-->
            <button
                id="menu-search-icon"
                class="inline-block ml-1 no-underline sm:ml-3 hover:text-black"
                @click.prevent="
                    searchOpen = !searchOpen;
                    $dispatch('search-open');
                "
                aria-label="<?= $escaper->escapeHtmlAttr(__('Toggle search form')) ?>"
                aria-haspopup="true"
                :aria-expanded="searchOpen"
                x-ref="searchButton"
            >
                <?= $heroicons->searchHtml(
                    "w-8 h-8 md:h-6 md:w-6 hover:text-black",
                    25,
                    25,
                    [
                        "aria-hidden" => "true"
                    ]
                ) ?>
            </button>

            <!--Customer Icon & Dropdown-->
            <?= $block->getChildHtml('customer') ?>

            <!--Cart Icon-->
            <?php if ($showMiniCart): ?>
                <button
            <?php else: ?>
                <a
            <?php endif ?>
                id="menu-cart-icon"
                class="relative inline-block ml-1 no-underline sm:ml-3 hover:text-black"
                x-ref="cartButton"
                :aria-disabled="isCartEmpty()"
                title="<?= $escaper->escapeHtmlAttr(__('Cart')) ?>"
                <?php if ($showMiniCart): ?>
                    @click.prevent.stop="() => {
                        $dispatch('toggle-cart', { isOpen: true })
                    }"
                    @toggle-cart.window="toggleCart($event)"
                    :aria-expanded="isCartOpen"
                    aria-haspopup="dialog"
                <?php else: ?>
                    href="<?= $escaper->escapeUrl($block->getUrl('checkout/cart/index')) ?>"
                <?php endif ?>
            >
                <span
                    class="sr-only label"
                    x-text="`
                        <?= $escaper->escapeHtml($showMiniCart ? __('Toggle minicart') : __('View cart')) ?>,
                        ${isCartEmpty() ?
                        '<?= $escaper->escapeHtml(__('Cart is empty')) ?>' :
                        hyva.str(
                            'You have %1 product%2 in your cart.',
                            cart.summary_count,
                            cart.summary_count === 1 ? '' : 's'
                        )}`
                    "
                >
                </span>

                <?= $heroicons->shoppingCartHtml(
                    "w-8 h-8 md:h-6 md:w-6 hover:text-black",
                    25,
                    25
                ) ?>

                <span
                    x-text="cart.summary_count"
                    x-show="!isCartEmpty()"
                    x-cloak
                    class="
                        absolute top-0 right-0 h-5 px-2 py-1 -mt-5 -mr-4 text-xs font-semibold
                        leading-none text-center text-white uppercase transform -translate-x-1
                        translate-y-1/2 rounded-full bg-primary
                    "
                    aria-hidden="true"
                ></span>
            <?php if ($showMiniCart): ?>
                </button>
            <?php else: ?>
                </a>
            <?php endif ?>

        </div>
    </div>
    <!--Search-->
    <div class="absolute z-10 w-full border-t shadow-sm bg-container-lighter border-container-lighter"
         id="search-content"
         x-cloak x-show="searchOpen"
         @click.outside="searchOpen = false"
         @keydown.escape="
            searchOpen = false;
            $refs.searchButton.focus();
         "
    >
        <?= $block->getChildHtml('header-search'); ?>
    </div>

    <!--Cart Drawer-->
    <?= $block->getChildHtml('cart-drawer'); ?>

    <!--Authentication Pop-Up-->
    <?= $block->getChildHtml('authentication-popup'); ?>
</div>

