<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Magento\Checkout\Block\Cart;
use Magento\Framework\Escaper;

/** @var Cart $block */
/** @var Escaper $escaper */

?>
<?php if (!$block->hasError()): ?>
    <?php $methods = $block->getMethods('methods') ?: $block->getMethods('top_methods') ?>
    <ul class="checkout methods items checkout-methods-items">
        <?php foreach ($methods as $method): ?>
            <?php $methodHtml = $block->getMethodHtml($method); ?>
            <?php if (trim($methodHtml) !== ''): ?>
                <li class="item"><?= /* @noEscape */ $methodHtml ?></li>
            <?php endif; ?>
        <?php endforeach; ?>
    </ul>
<?php endif; ?>
