<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\CurrentProduct;
use Hyva\Theme\ViewModel\HeroiconsOutline;
use Hyva\Theme\ViewModel\ProductAlert;
use Magento\Catalog\Model\Product;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Escaper $escaper */
/** @var Template $block */
/** @var ViewModelRegistry $viewModels */

/** @var ProductAlert $productAlertViewModel */
$productAlertViewModel = $viewModels->require(ProductAlert::class);

/** @var CurrentProduct $currentProduct */
$currentProduct = $viewModels->require(CurrentProduct::class);

/** @var HeroiconsOutline $heroicons */
$heroicons = $viewModels->require(HeroiconsOutline::class);

/** @var Product $product */
$product = $currentProduct->get();

if (!$product->getId() || !$productAlertViewModel->showPriceAlert($product)) {
    return;
}

$signupLabel = __("Notify me when the price drops");
?>
<div class="product alert price text-right">
    <a href="<?= $escaper->escapeUrl($productAlertViewModel->getSaveUrl($product, 'price')) ?>"
       title="<?= $escaper->escapeHtml($signupLabel) ?>" class="action alert">
        <span class="text-orange-400">
            <?= $heroicons->bellHtml('w-6 h-6 inline') ?>
        </span>
        <span class="underline">
            <?= $escaper->escapeHtml($signupLabel) ?>
        </span>
    </a>
</div>
