<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HeroiconsSolid;
use Magento\Framework\Escaper;
use Magento\Wishlist\Block\Cart\Item\Renderer\Actions\MoveToWishlist;

/** @var MoveToWishlist $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

/** @var HeroiconsSolid $heroicons */
$heroicons = $viewModels->require(HeroiconsSolid::class);

?>
<?php if ($block->isAllowInCart() && $block->isProductVisibleInSiteVisibility()): ?>
    <a href="#"
       class="towishlist hover:text-red-600"
       x-data="{}"
       @click.prevent='hyva.postForm(<?= /* @noEscape */ $block->getMoveFromCartParams() ?>)'
    >
        <?= $heroicons->heartHtml('w-6 h-6') ?>
        <span class="sr-only">
            <?= $escaper->escapeHtml(__('Move to Wishlist')) ?>
        </span>
    </a>
<?php endif ?>
