<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HeroiconsOutline;
use Magento\Downloadable\Block\Customer\Products\ListProducts;
use Magento\Downloadable\Model\Link\Purchased\Item;
use Magento\Framework\Escaper;
use Magento\Framework\View\Helper\SecureHtmlRenderer;

// phpcs:disable Generic.Files.LineLength.TooLong
// phpcs:disable Generic.WhiteSpace.ScopeIndent.Incorrect

/** @var ListProducts $block */
/** @var Escaper $escaper */
/** @var SecureHtmlRenderer $secureRenderer */
/** @var ViewModelRegistry $viewModels */

/** @var HeroiconsOutline $heroicons */
$heroicons = $viewModels->require(HeroiconsOutline::class);
?>
<h2 id="downloadableProducts" class="text-2xl mb-6"><?= $escaper->escapeHtml(__('My Downloadable Products')) ?></h2>
<?php $items = $block->getItems(); ?>
<?php if (count($items)): ?>
    <div class="overflow-x-auto card mb-4">
        <table
            id="my-orders-table"
            class="downloadable-products w-full sm:table-fixed lg:table-auto"
            aria-labelledby="downloadableProducts"
        >
            <thead class="text-sm text-secondary">
                <tr>
                    <th class="p-2 text-start">
                        <?= $escaper->escapeHtml(__('Order #')) ?>
                    </th>
                    <th class="p-2 text-start hidden lg:table-cell">
                        <?= $escaper->escapeHtml(__('Date')) ?>
                    </th>
                    <th class="p-2 text-start hidden lg:table-cell">
                        <?= $escaper->escapeHtml(__('Title')) ?>
                    </th>
                    <th class="p-2 text-start hidden lg:table-cell">
                        <?= $escaper->escapeHtml(__('Download')) ?>
                    </th>
                    <th class="p-2 text-start hidden lg:table-cell">
                        <?= $escaper->escapeHtml(__('Status')) ?>
                    </th>
                    <th class="p-2 text-start">
                        <?= $escaper->escapeHtml(__('Remaining Downloads')) ?>
                    </th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($items as $item): ?>
                    <tr class="align-top even:bg-container-darker">
                        <th
                            class="p-2 text-start font-normal"
                            aria-label="<?= $escaper->escapeHtmlAttr($item->getPurchased()->getOrderIncrementId()) ?>"
                        >
                            <a
                                id="downloadableProduct<?= $escaper->escapeHtmlAttr($item->getPurchased()->getOrderId()) ?>"
                                href="<?= $escaper->escapeUrl($block->getOrderViewUrl($item->getPurchased()->getOrderId()))?>"
                                title="<?= $escaper->escapeHtml(__('View Order')) ?>"
                                aria-label="<?= $escaper->escapeHtmlAttr(__('View order') . ' ' . $item->getPurchased()->getOrderIncrementId()) ?>"
                            ><?= $escaper->escapeHtml($item->getPurchased()->getOrderIncrementId()) ?></a>
                        </th>
                        <td class="p-2 hidden lg:table-cell">
                            <?php
                                $date = $item->getPurchased()->getCreatedAt();
                                $format = $block->getDateFormat() ?: \IntlDateFormatter::SHORT;
                                $formatLong = $block->getDateFormat() ?: \IntlDateFormatter::LONG;
                            ?>
                            <time datetime="<?= $escaper->escapeHtmlAttr($block->formatDate($date, $format)); ?>">
                                <span aria-hidden="true"><?= $escaper->escapeHtml($block->formatDate($date, $format)); ?></span>
                                <span class="sr-only">
                                    <?= $escaper->escapeHtml($block->formatDate($date, $formatLong)); ?>
                                </span>
                            </time>
                        </td>
                        <td class="p-2 hidden lg:table-cell">
                            <?= $escaper->escapeHtml($item->getPurchased()->getProductName()) ?>
                        </td>
                        <td class="p-2 hidden lg:table-cell">
                            <?php if ($item->getStatus() == Item::LINK_STATUS_AVAILABLE): ?>
                                <a
                                    href="<?= $escaper->escapeUrl($block->getDownloadUrl($item)) ?>"
                                    class="inline-block text-sm underline text-secondary-darker"
                                    id="download_<?= /* @noEscape */ $item->getPurchased()->getProductId() ?>"
                                    title="<?= $escaper->escapeHtmlAttr(__('Start Download')) ?>"
                                    aria-label="<?= $escaper->escapeHtmlAttr(__('Start Download')) ?>"
                                    class="action download"
                                >
                                    <?= $heroicons->documentDownloadHtml(); ?>
                                </a>
                                <?php if ($block->getIsOpenInNewWindow()): ?>
                                    <?= /* @noEscape */ $secureRenderer->renderEventListenerAsTag(
                                        'onclick',
                                        "this.target='_blank'",
                                        'a#download_' . $item->getPurchased()->getProductId()
                                    ) ?>
                                <?php endif; ?>
                            <?php endif; ?>
                        </td>
                        <td class="p-2 hidden lg:table-cell">
                            <?= $escaper->escapeHtml(__(ucfirst($item->getStatus()))) ?>
                        </td>
                        <td class="p-2">
                            <?= $escaper->escapeHtml($block->getRemainingDownloads($item)) ?>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
    <?php if ($block->getChildHtml('pager')): ?>
        <div class="toolbar downloadable-products-toolbar bottom">
            <?= $block->getChildHtml('pager') ?>
        </div>
    <?php endif; ?>
<?php else: ?>
    <div class="message info empty">
        <span><?= $escaper->escapeHtml(__('You have not purchased any downloadable products yet.')) ?></span>
    </div>
<?php endif; ?>

<div class="actions-toolbar">
    <div class="secondary">
        <a href="<?= $escaper->escapeUrl($block->getBackUrl()) ?>" class="action back">
            <span><?= $escaper->escapeHtml(__('Back')) ?></span>
        </a>
    </div>
</div>
