# Defaults
variables:
  SRC_DIR: '.'

include:
  -  project: 'hyva-themes/base-ci'
     file: 'lint/php.yml'
     ref: main
  -  project: 'hyva-themes/base-ci'
     file: 'static/phpcs.yml'
     ref: main
  -  project: 'hyva-themes/base-ci'
     file: 'test/integration.yml'
     ref: main
  -  project: 'hyva-themes/base-ci'
     file: 'test/cypress.yml'
     ref: main

test:integration:
    extends: .test:integration
    parallel:
        matrix:
            # Note: 2.4.0 fails due to a bug in dotmailer/dotmailer-magento2-extension integration tests
            - MAGEVERSION: ['2.4.5-p1']

test:cypress:
    extends: .test:cypress
    parallel:
        matrix:
            # Note: The cypress tests do not pass on 2.4.0 because the customer API is missing the login feature
            # Note: The cypress tests do not pass on 2.4.1 because the missing add coupon success message
            - MAGEVERSION: ['2.4.5-p1']
