<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HeroiconsOutline;
use Magento\Framework\Escaper;
use Magento\Sales\Block\Order\Info\Buttons;

/** @var Escaper $escaper */
/** @var Buttons $block */
/** @var ViewModelRegistry $viewModels */

/** @var HeroiconsOutline $heroicons */
$heroicons = $viewModels->require(HeroiconsOutline::class);
?>
<div class="flex items-center justify-center md:justify-end my-4 md:my-0">
    <?php $order = $block->getOrder() ?>
    <a href="<?= $escaper->escapeUrl($block->getUrl('*/*/printInvoice', ['order_id' => $order->getId()])) ?>"
       class="ml-6 btn btn-secondary text-secondary-darker"
       target="_blank"
       rel="noopener">
        <?= $heroicons->printerHtml('mr-1 inline-block'); ?>
        <span><?= $escaper->escapeHtml(__('Print All Invoices')) ?></span>
    </a>
    <?= $block->getChildHtml() ?>
</div>
