<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Magento\Catalog\Block\Product\View\BaseImage;
use Magento\Catalog\Pricing\Price\TierPrice;
use Magento\Framework\Escaper;
use Magento\GroupedProduct\Block\Product\View\Type\Grouped;

/**
 * @var BaseImage $block
 * @var Grouped $block
 * @var Escaper $escaper
 */

$block->setPreconfiguredValue();
$product = $block->getProduct();
$associatedProducts = $block->getAssociatedProducts();
$hasAssociatedProducts = count($associatedProducts) > 0;
?>
<script>
    function initGroupedOptions() {
        return {
            isValid: true,
            validateForm() {
                const validateInputs = Array.from(
                    document.querySelectorAll('input[name^=super_group]')
                );

                // at least one of the inputs has to have a qty > 0
                this.isValid = validateInputs.filter(
                    input => input.value > 0
                ).length;

                // we set or unset validity for all fields at once
                // and empty string un-sets invalidity
                validateInputs.map(input =>
                    input.setCustomValidity(this.isValid ?
                        "" :
                        "<?= $escaper->escapeJs(__('Please specify the quantity of product(s).')) ?>")
                )

                if (!this.isValid) {
                    // this triggers an immediate display of the form errors
                    document.querySelector("#product_addtocart_form").reportValidity();
                    return false;
                }
                return true;
            },
            init() {
                document.querySelector("#product_addtocart_form")
                    .addEventListener("submit", (e) => {
                        // don't submit on errors
                        if (!this.validateForm()) {
                            e.preventDefault();
                        }
                    });
            }
        }
    }
</script>
<div class="my-12" x-data="initGroupedOptions()">
<?php if ($hasAssociatedProducts): ?>
    <h2 class="text-gray-900 text-xl title-font font-medium mb-2">
        <?= $escaper->escapeHtml(__('Grouped product items')) ?>
    </h2>
    <div class="hidden sm:flex py-2 border-t border-gray-300
        w-full items-center justify-between gap-2"
    >
        <div class="text-gray-500 font-semibold text-left">
            <?= $escaper->escapeHtml(__('Product Name')) ?>
        </div>
        <div class="text-gray-500 font-semibold text-left w-20">
            <?= $escaper->escapeHtml(__('Qty')) ?>
        </div>
    </div>

    <?php foreach ($associatedProducts as $item): ?>
        <div class="flex flex-wrap border-t border-gray-300
            py-2 w-full items-center justify-between gap-2"
        >
            <label
                class="text-gray-700 text-left"
                for="super_group[<?= $escaper->escapeHtmlAttr($item->getId()) ?>]"
            >
                <span class="product-item-name font-semibold">
                    <?= $escaper->escapeHtml($item->getName()) ?>
                </span>
                <?php if ($block->getCanShowProductPrice($product)): ?>
                    <?php if ($block->getCanShowProductPrice($item)): ?>
                        <?= /* @noEscape */ $block->getProductPrice($item) ?>
                    <?php endif; ?>
                <?php endif; ?>
            </label>
            <div class="label text-gray-900 text-left sm:text-right w-full sm:w-20">
                <?php if ($product->isSaleable()): ?>

                    <?php if ($item->isSaleable()): ?>
                        <div class="control qty">
                            <input type="number"
                                   min="0"
                                   name="super_group[<?= $escaper->escapeHtmlAttr($item->getId()) ?>]"
                                   id="super_group[<?= $escaper->escapeHtmlAttr($item->getId()) ?>]"
                                   value="<?= $escaper->escapeHtmlAttr($item->getQty() * 1) ?>"
                                   title="<?= $escaper->escapeHtmlAttr(__('Qty')) ?>"
                                   class="qty form-input px-2 py-2 w-20 text-center"
                                   :class=" { 'border-red-500 focus:border-red-500 focus:ring-red-500': !isValid }"
                                   @input.debounce="validateForm()"
                            />
                        </div>
                    <?php else: ?>
                        <div class="stock unavailable"
                             title="<?= $escaper->escapeHtmlAttr(__('Availability')) ?>"
                        >
                            <?= $escaper->escapeHtml(__('Out of stock')) ?>
                        </div>
                    <?php endif; ?>

                <?php endif; ?>
            </div>

            <?php if ($block->getCanShowProductPrice($product)
                && $block->getCanShowProductPrice($item)
                && trim($block->getProductPriceHtml(
                    $item,
                    TierPrice::PRICE_CODE
                ))): ?>
                <div class="flex pt-2 w-full items-center">
                    <?= $block->getProductPriceHtml(
                        $item,
                        TierPrice::PRICE_CODE
                    ) ?>
                </div>
            <?php endif; ?>

        </div>
    <?php endforeach; ?>
<?php else: ?>
    <?= $escaper->escapeHtml(__('No options of this product are available.')) ?>
<?php endif; ?>
</div>
