<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HeroiconsSolid;
use Hyva\Theme\ViewModel\Store;
use Hyva\Theme\ViewModel\StoreSwitcher;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use Magento\Store\ViewModel\SwitcherUrlProvider;

// phpcs:disable Generic.Files.LineLength.TooLong

/** @var Template $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

/** @var HeroiconsSolid $heroiconsSolid */
$heroiconsSolid = $viewModels->require(HeroiconsSolid::class);

/** @var SwitcherUrlProvider $switcherUrlProvider */
$switcherUrlProvider = $viewModels->require(SwitcherUrlProvider::class);

/** @var Store $storeViewModel */
$storeViewModel = $viewModels->require(Store::class);

/** @var StoreSwitcher $storeSwitcherViewModel */
$storeSwitcherViewModel = $viewModels->require(StoreSwitcher::class);

$currentStore = $storeSwitcherViewModel->getStore();
?>
<?php if (count($storeSwitcherViewModel->getGroups()) > 1): ?>
    <div x-data="{ open: false }"
         class="w-full sm:w-1/2 md:w-full"
    >
        <div class="title-font font-medium text-gray-900 tracking-widest text-sm mb-3 uppercase">
            <?= $escaper->escapeHtml(__('Select Store')) ?>
        </div>
        <div class="relative inline-block text-left">
            <div>
            <?php foreach ($storeSwitcherViewModel->getGroups() as $group): ?>
                <?php if ($group->getId() == $storeSwitcherViewModel->getCurrentGroupId()): ?>
                <button @click.prevent="open = !open"
                        @click.outside="open = false"
                        @keydown.window.escape="open=false"
                        type="button"
                        class="inline-flex justify-center w-full form-select px-4 py-2 bg-white focus:outline-none"
                        aria-haspopup="true"
                        aria-expanded="true"
                >
                    <?= $escaper->escapeHtml($group->getName()) ?>
                    <?= $heroiconsSolid->chevronDownHtml("flex self-center h-5 w-5 -mr-1 ml-2", 25, 25) ?>
                </button>
                <?php endif; ?>
            <?php endforeach; ?>
            </div>
            <nav x-cloak=""
                 x-show="open"
                 class="absolute right-0 top-full z-20 w-56 py-2 mt-1 overflow-auto origin-top-left rounded-sm shadow-lg sm:w-48 lg:mt-3 bg-container-lighter">
                <div class="my-1" role="menu" aria-orientation="vertical" aria-labelledby="options-menu">
                    <?php foreach ($storeSwitcherViewModel->getGroups() as $group): ?>
                        <?php if (!($group->getId() == $storeSwitcherViewModel->getCurrentGroupId())): ?>
                            <a href="<?= $escaper->escapeUrl($switcherUrlProvider->getTargetStoreRedirectUrl($group->getDefaultStore())) ?>"
                               class="block px-4 py-2 lg:px-5 lg:py-2 hover:bg-gray-100"
                            >
                                <?= $escaper->escapeHtml($group->getName()) ?>
                            </a>
                        <?php endif; ?>
                    <?php endforeach; ?>
                </div>
            </nav>
        </div>
    </div>
<?php endif; ?>
